baseURL: https://nyxgear.com
languageCode: en-us
title: nyxgear
theme: "PaperMod"
params:
  defaultTheme: dark
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  homeInfoParams:
    Title: Hi there wave
    Content: Can be Info, links, about...

  socialIcons: # optional
    - name: "<platform>"
      url: "<link>"
    - name: "<platform 2>"
      url: "<link2>"
  ShowReadingTime: true

  outputs:
    home:
      - HTML
      - RSS
      - JSON # is necessary for search

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    # - identifier: categories
    #   name: ~/categories
    #   url: /categories/
    #   weight: 10
    - identifier: about
      name: $ whoami
      url: /about/
      weight: 10
    - identifier: archives
      name: ~/archives
      url: /archives/
      weight: 40
    - identifier: tags
      name: ~/tags
      url: /tags/
      weight: 50
    - identifier: search
      name: find ~/ 
      url: /search/
      weight: 60