baseURL: https://nyxgear.com
languageCode: en-us
title: nyxgear
theme: PaperMod
params:
  defaultTheme: light
  DateFormat: "2006-01-02"
  ShowShareButtons: true
  homeInfoParams:
    Title: Hi, I'm Stefano
    Content: Software Engineer automating stuff on Linux with git, Docker, and K8S 

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/nyxgear"
    - name: "gitlab"
      url: "https://gitlab.com/nyxgear"
    - name: "twitter"
      url: "https://twitter.com/nyxgear"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/stefano-cilloni/"

  ShowCodeCopyButtons: true
  ShowReadingTime: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]
  
  # posts' params
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true
  ShowRssButtonInSectionTermList: true

  showToc: true
  TocOpen: true
  UseHugoToc: true

  editPost:
    URL: "https://github.com/nyxgear/nyxgear-website/tree/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

googleAnalytics: UA-47276148-1

permalinks:
  posts: /:year/:month/:title/

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary for search

menu:
  main:
    # - identifier: categories
    #   name: ~/categories
    #   url: /categories/
    #   weight: 10
    - identifier: home
      name: cd $HOME
      url: /
      weight: 1
    - identifier: about
      name: $ whoami
      url: /about/
    - identifier: archives
      name: ~/archives
      url: /archives/
      weight: 40
    - identifier: tags
      name: ~/tags
      url: /tags/
      weight: 50
    - identifier: search
      name: find ~/ 
      url: /search/
      weight: 60