name: Hugo build, deploy to Netlify

on:
  push:
    branches:    
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Let's fetch only what it is required.

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.99.1'

      - name: Hugo build
        run: hugo --minify

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2.3
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "GitHub Actions deploying commit: ${{ github.event.head_commit.message }}"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        timeout-minutes: 1

      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
